export const CREATE_RECIPE = 'CREATE_RECIPE'
export const EDIT_RECIPE = 'EDIT_RECIPE'
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS'
export const FETCH_RECIPES_FAILED = 'FETCH_RECIPES_FAILED'
export const FETCH_RECIPES_PENDING = 'FETCH_RECIPES_PENDING'
export const SELECT_RECIPE = 'SELECT_RECIPE'
export const CREATE_RECIPE_ERROR = 'CREATE_RECIPE_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'
export const FETCH_RECIPES_BY_ID_SUCCESS = 'FETCH_RECIPES_BY_ID_SUCCESS'
export const FETCH_RECIPES_BY_ID_PENDING = 'FETCH_RECIPES_BY_ID_PENDING'
export const FETCH_RECIPES_BY_ID_FAILED = 'FETCH_RECIPES_BY_ID_FAILED'





