export const CREATE_RECIPE = 'CREATE_RECIPE'
export const EDIT_RECIPE = 'EDIT_RECIPE'
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS'
export const FETCH_RECIPES_FAILED = 'FETCH_RECIPES_FAILED'
export const FETCH_RECIPES_PENDING = 'FETCH_RECIPES_PENDING'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const SELECT_RECIPE = 'SELECT_RECIPE'



